### ISSUE TITLE
Gallery view do not work with Conversations 2.9.0 and Tb 38.0.1

### ISSUE THREAD

**Issue by KenjiroPL** [protz/GMail-Conversation-View#971]
When using gallery view to show attached images, i'm receiving this error in log:

Czas: 2015-06-17 14:39:13
Błąd: TypeError: $(...).tmpl is not a function
Plik źródłowy: chrome://conversations/content/gallery/js/gallery.js
Wiersz: 103

Is it something i can fix myself, or not?

**Comment by protz** [comment]
Please install the latest version from http://jonathan.xulforum.org/files/gcv-nightlies/ ; I need to upload a new release...

**Comment by KenjiroPL** [comment]
Thanks, it works.
